context:
  pyproject: ${{ load_from_file("../pyproject.toml") }}

package:
  name: ${{ pyproject.project.name }}
  version: ${{ pyproject.project.version }}

source:
  path: ../

build:
  noarch: python
  script: pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python ${{ pyproject.project["requires-python"] }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python ${{ pyproject.project["requires-python"] }}

tests:
  - python:
      imports:
        - ${{ pyproject.project.name | replace("-", "_") }}
