package:
  name: {{ cookiecutter.project_slug }}
  version: "1.0.0"
about:
  home: {{ cookiecutter.github_url }}
  license: MIT
  summary:
source:
  git_url: ../
build:
  script: {% raw %}"{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."{% endraw %}
  noarch: python
requirements:
  build:
    - python >=3.8
    - build
    - setuptools
    - setuptools-scm
  run:
    - python >=3.8
test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
